# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0007_statuscheckresult_consecutive_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='authorization_header',
            field=models.TextField(blank=True, help_text=b'Authorization header.', null=True),
        ),
    ]
